# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sd_source' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sd_source

  pod 'SDWebImage', '5.15.7'
  target 'sd_sourceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sd_sourceUITests' do
    # Pods for testing
  end

end
